config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    root 'homes#index'
    devise_for :users
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :videos, only: [:show, :index]
    resources :nasas, only: [:index]
    resources :pictures, except: [:edit, :update, :destroy]
    resources :users, only: [:show, :destroy, :index]
    resources :topics, only: [:show, :index]
    resources :meetings, except: [:edit, :update, :destroy]
    resources :weathers, only: [:index]
    resources :conversations, only: [:create, :index] do
      resources :messages, only: [:new, :create, :index]
    end

    namespace :api do
      namespace :v1 do
        resources :videos, only: [:index]
        resources :nasas, only: [:index]
      end
    end

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
    belongs_to :sender, :foreign_key => :sender_id, class_name: "User"
    belongs_to :recipient, :foreign_key => :recipient_id, class_name: "User"

    has_many :messages, dependent: :destroy

    validates_uniqueness_of :sender_id, :scope => :recipient_id

    scope :between, -> (sender_id,recipient_id) do
      where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
    end

end

app/models/meeting.rb
class Meeting < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true
  validates :start_time, presence: true

  belongs_to :user


end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :conversation
    belongs_to :user

    validates_presence_of :body, :conversation_id, :user_id

    def message_time
      created_at.strftime("%m/%d/%y at %l:%M %p")
    end
end

app/models/nasa.rb
class Nasa < ApplicationRecord
  validates :date, presence: true
  validates :explanation, presence: true
  validates :title, presence: true
  validates :url, presence: true
end

app/models/picture.rb
class Picture < ApplicationRecord
  validates :photo, presence: true
  validates :title, presence: true
  validates :explanation, presence: true

  belongs_to :user

  mount_uploader :photo, ClassroomPictureUploader

end

app/models/topic.rb
class Topic < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true
  validates :meta_topic, presence: true
  validates :sub_topic, presence: true

end


# has_many :sub_topics

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
  validates :password, presence: true

  has_many :conversations, :foreign_key => :sender_id
  has_many :meetings
  has_many :pictures

end

app/models/video.rb
class Video < ApplicationRecord
  validates :youtube_id, presence: true
  validates :title, presence: true
  validates :description, presence: true
  validates :video_id, presence: true



  def self.search(search)
  where("youtube_id LIKE ? OR title LIKE ? OR description LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%")
  end

end

app/models/weather.rb
class Weather < ApplicationRecord


end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  protect_from_forgery unless: -> { request.format.json? }
end

# Fetch Request Options
# We will also want to add some additional options to our fetch requests so that they are handled by Rails effectively.
#
# Let's say we are reviewing fruits. We want to make a request to POST a new fruit, so that we can review this fruit in the future.
#
# With POST requests in particular, its important we have the right options passed along.Make sure that you have both the credentials option and headers options below.
#
# fetch(`/api/v1/fruits.json`, {
#       credentials: 'same-origin',
#       method: 'POST',
#       body: JSON.stringify(formPayload),
#       headers: { 'Accept': 'application/json', 'Content-Type': 'application/json' }
#     })
#     ...
# This way, our Rails application knows to trust this fetch request, and know that its from our frontend React application.
#
# Note also that because of the earlier protect_from_forgery step, our urls will have to end in .json. This won't change your routes.rb, but it will have to be added in your fetch paths!

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController

  def index
    @meetings = Meeting.all
  end

  def new
    @meeting = Meeting.new
    @user = current_user
  end

  def create
    @meeting = current_user.meetings.create(meeting_params)

    if @meeting.save
      flash[:notice] = "Meeting added successfully"
       redirect_to @meeting
    else
      render "new"
    end
  end

  def show
    @meeting = Meeting.find(params[:id])
  end

  private

  def meeting_params
    params.require(:meeting).permit(:title, :description, :start_time)
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action do
   @conversation = Conversation.find(params[:conversation_id])
  end

  def index
    @messages = @conversation.messages
    if @messages.length > 10
     @over_ten = true
     @messages = @messages[-10..-1]
    else
     @over_ten = false
     @messages = @conversation.messages
    end
   if @messages.last.user_id != current_user[:id]
     @messages.last.read = true;
   end
    @message = @conversation.messages.new
   end

  def new
   @message = @conversation.messages.new
  end

  def create
   @message = @conversation.messages.new(message_params)
   if @message.save
    redirect_to conversation_messages_path(@conversation)
   end
  end

private

   def message_params
    params.require(:message).permit(:body, :user_id)
   end
end

app/controllers/nasas_controller.rb
class NasasController < ApplicationController
  def index
    @nasas = Nasa.all
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

  def index
    @pictures = Picture.all
  end

  def new
    @picture = Picture.new
    @user = current_user
  end

  def create
    @picture = current_user.pictures.create(picture_params)

    if @picture.save
      flash[:notice] = "Picture added successfully"
       redirect_to @picture
    else
      render "new"
    end
  end

  def show
    @picture = Picture.find(params[:id])
  end

  private

  def picture_params
    params.require(:picture).permit(:photo, :title, :explanation)
  end

end

app/controllers/topics_controller.rb
class TopicsController <ApplicationController

  def index
    @topics = Topic.all
  end

  def show
    @topic_choice = Topic.find(params[:id])
    @topics = Topic.all
    @topic = @topics.where(title: @topic_choice.title)
    @videos = Video.all
    @video_array = []
      @topic.each do |t|
        @videos.each do |v|
          if v.video_id == t.sub_topic
            @video_array << v
          end
        end
      end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize_user, except: [:index, :show]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy.id
    redirect_to park_path(parks), notice: 'User has been terminated!'
  end

  private
  ##I've commented this out as I might need it in the future?
  # def user_params
  #   params.require(:user).permit(:username, :first_name, :last_name, :email, :date_of_birth, :user_photo)
  # end

  def authorize_user
    if !current_user.superadmin_role
      raise ActionController::RoutingError.new("You are not authorized to do that!")
    end
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def index
    @videos = Video.all
  end

  def show
    @videos = Video.find(params[:id])
  end

end

app/controllers/weathers_controller.rb
class WeathersController < ApplicationController


  def index

  end

end

app/helpers/nasas_helper.rb
module NasasHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/meetings/index.html.erb
<div class="calendar">
<%= month_calendar events: @meetings do |date, meetings| %>
  <%= date.day %>
  <% meetings.each do |meeting| %>
    <div>
      <%= link_to meeting.title, meeting_path(meeting)%>
    </div>
  <% end %>

<% end %>
</div>

app/views/meetings/new.html.erb
<h1 class="sign-up-title">New Meeting Form</h1>

<% if @meeting.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

    <ul>
      <% @meeting.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for(@meeting) do |f| %>
  <div class="reg-form">
    <div>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
    </div>

    <div>
    <%= f.label :description %><br />
    <%= f.text_field :description %>
    </div>


    <!-- <div>
      <%= f.label "Due date *(please enter yyyy-mm-dd)" %><br>
      <%= select_date Date.today, prefix: :start_date %>
    </div> -->

    <div>
        <%= f.label :start_date %>
        <%= f.date_field :start_time, required: true %>
    </div>

    <%= f.submit "Add Meeting"%>
  </div>
<% end %>

app/views/meetings/show.html.erb
<p class="homework-title" id="nasa-tile__title"><strong><%= @meeting.title %></strong></p>
<p class="homework-description" id="nasa-tile__title"><%= @meeting.description %></p>

app/views/messages/index.html.erb
<% if @over_ten %>
 <%= link_to "Show Previous", "?m=all" %>
<% end %>
<div class=”ui segment”>
 <% @messages.each do |message| %>
  <% if message.body %>
   <% user = User.find(message.user_id) %>
   <div class=”message-item”>
    <div class=”content”>
     <div class=”header” id="message-box"><strong><%= user.first_name %></strong>     <%= message.message_time %></div>
      <div class=”list”>
       <div class=”message-content”>
        <i class=”right triangle icon” id="message-content"></i>
         <%= message.body %>
      </div>
    </div>
   </div>
 </div>
 <% end %>
<% end %>
</div>
<%= form_for [@conversation, @message], html: {class: "ui reply form"} do |f| %>
 <div class=”field”>
   <%= f.text_area :body, class: "form-control" %>
 </div>
 <%= f.text_field :user_id, value: current_user.id, type: "hidden" %>
 <div>
   <%= f.submit "Send", class: "ui blue labeled submit icon button" %>
 </div>
<% end %>

app/views/topics/index.html.erb
<% topic_lessons = [] %>
<% topic_lessons << @topics.first %>
<% @topics.each do |topic| %>
    <% if topic_lessons.last.title != (topic.title) %>
    <% topic_lessons << topic %>
    <% end %>
<% end %>

<ul class="topic-tile-list">
  <% topic_lessons.each do |topic| %>
    <div class="topic-tile">
      <p class="topic-button"><%= link_to "#{topic.title}", topic_path(topic) %></p>
    </div>
  <% end %>
</ul>

app/views/topics/show.html.erb
<h2 id="topic-titlish"><%= @topic.first.title %></h2>
<h3 id="topic-descriptionish"><%= @topic.first.description %></h3>


<% @video_array.each do |video| %>
  <div class="video-tile-maker">
    <p id="video-tile__title"><%= video.title %>:</p>

    <div class="flex-video widescreen vimeo">
      <iframe src="https://www.youtube-nocookie.com/embed/<%= video.youtube_id %>?rel=0" width="400" height="225" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
    </div>
    <p id="video-tile__description"><%= video.description %></p>
  </div></br>
<% end %>

app/views/users/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SimpleMessagesApp</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="ui grid">
    <div class="row">
      <div class="fourteen wide centered column">
        <h2 class="ui header">
          <i class="mail icon"></i>
          <div class="content">
            Simple Messaging App
          </div>
        </h2>
        <div class="ui purple inverted menu">
          <i class="home icon"></i><%= link_to "Home", root_path, class: "item" %>
            <% if current_user %>
              <%= link_to "Mailbox", conversations_path, class: "item" %>
              <div class="right menu">
                <%= link_to 'Sign Out', signout_path, class: "item" %>
              </div>
            <% else %>
              <div class="right menu">
                <%= link_to 'Sign Up', signup_path, class: "item" %>
                <%= link_to "Sign-In", signin_path, class: "item" %>
              </div>
            <% end %>
        </div>

        <%= yield %>
      </div>
    </div>
  </div>



</body>
</html>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SimpleMessagesApp</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="ui grid">
    <div class="row">
      <div class="fourteen wide centered column">
        <h2 class="ui header">
          <i class="mail icon"></i>
          <div class="content profile-home-button">
            Hi, <%= current_user.first_name %>!
          </div>
        </h2>
        <div class="ui purple inverted menu">
          <i class="home icon"></i><%= link_to "Home", root_path, class: "item" %> </br>
              <%= link_to "Mailbox", conversations_path, class: "item" %></br>
              <%if current_user.admin?%>
              <%= link_to 'Add Class Pictures', new_picture_path, class: "item" %></br>
              <%= link_to 'Add An Assignment', new_meeting_path, class: "item" %>
              <%end%>

        </div>

        <%= yield %>
      </div>
    </div>
  </div>




</body>
</html>

<!-- <%if current_user.try(:superadmin_role)%>
  <%= link_to 'Terminate User', user_path(@user.id), method: :delete, data: { confirm: 'Are you sure?' } %>
<%end%> -->

app/views/weathers/index.html.erb
<div class="map-embed">
<script src='https://darksky.net/map-embed/@emoji,42.3601,-71.0589,8.js?embed=true&timeControl=true&fieldControl=true&defaultField=emoji'></script>
</div>