config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    root 'homes#index'
    devise_for :users
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :videos, only: [:show, :index]
    resources :nasas, only: [:index]
    resources :pictures, except: [:edit, :update, :destroy]
    resources :users, only: [:show, :destroy, :index]
    resources :topics, only: [:show, :index]
    resources :meetings, except: [:edit, :update, :destroy]
    resources :weathers, only: [:index]
    resources :conversations, only: [:create, :index] do
      resources :messages, only: [:new, :create, :index]
    end

    namespace :api do
      namespace :v1 do
        resources :videos, only: [:index]
        resources :nasas, only: [:index]
      end
    end

  end
end

app/models/video.rb
class Video < ApplicationRecord
  validates :youtube_id, presence: true
  validates :title, presence: true
  validates :description, presence: true
  validates :video_id, presence: true



  def self.search(search)
  where("youtube_id LIKE ? OR title LIKE ? OR description LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%")
  end

end

app/controllers/api/v1/videos_controller.rb
class Api::V1::VideosController < ApiController
  def index
    render json: Video.all
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def index
    @videos = Video.all
  end

  def show
    @videos = Video.find(params[:id])
  end

end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/index.html.erb
<!-- <%= form_tag(videos_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search Videos" %>
    <%= submit_tag "Search", :name => nil %>
<% end %>

<% if @videos.blank? %>
  <h4>There are no videos containing the term <%= params[:search] %>.</h4>
<% end %> -->
<li class="my-profile"><%= link_to '3rd Grade Strategies', video_path("cc-3rd-strategies-for-adding-two-and-three-digit-numbers") %></li>



<% @videos.each do |video| %>
  <div class="video-tile-maker">
    <p id="video-tile__title"><%= video.title %>: </br> <%= video.description %></p>
    <p><a href="#" data-reveal-id="videoModal<%= video.youtube_id %>" className="radius button"><%= video.title %>&hellip;</a></p>
    <div id="videoModal<%= video.youtube_id %>" class="reveal-modal medium" data-reveal aria-labelledby="videoModalTitle" aria-hidden="true" role="dialog">
      <h2 id="videoModalTitle">Khan Video</h2>
      <div class="flex-video widescreen vimeo">
        <iframe width="1280" height="720" src="https://www.youtube-nocookie.com/embed/<%= video.youtube_id %>?rel=0" frameborder="0" allowfullscreen></iframe>
      </div>

      <a class="close-reveal-modal" aria-label="Close">&#215;</a>
    </div>
  </div>
<% end %>



<!-- <div id="app"></div> -->

app/views/videos/show.html.erb
<% @videos.each do |video| %>
  <div class="video-tile-maker">
    <p id="video-tile__title"><%= video.title %></p>
    <p id="video-tile__description"><%= video.description %></p>
    <p id="video-tile__youtube_id"><%= video.youtube_id %></p>
    <p id="video-tile__lesson_slug"><%= video.lesson_slug %></p>
    <p><a href="#" data-reveal-id="videoModal<%= video.youtube_id %>" className="radius button"><%= video.title %>&hellip;</a></p>
    <div id="videoModal<%= video.youtube_id %>" class="reveal-modal medium" data-reveal aria-labelledby="videoModalTitle" aria-hidden="true" role="dialog">
      <h2 id="videoModalTitle">Khan Video</h2>
      <div class="flex-video widescreen vimeo">
        <iframe width="1280" height="720" src="https://www.youtube-nocookie.com/embed/<%= video.youtube_id %>?rel=0" frameborder="0" allowfullscreen></iframe>
      </div>

      <a class="close-reveal-modal" aria-label="Close">&#215;</a>
    </div>
  </div>
<% end %>